name 'owca-ecommerce'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures owca-ecommerce'
long_description 'Installs/Configures owca-ecommerce'
version '1.0.0'
depends 'java', '= 1.42.0'
